// Public Supabase browser configuration for 67 Royale.
// Never put service-role or secret keys in this file.
window.SUPABASE_URL = 'https://pbokbnixktqmmtigehul.supabase.co';
window.SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_552EmITFZ9A7XDm1P43cWg_cbSWF_Vg';
window.SITE_URL_67 = 'https://67.mel-m-ozturk.workers.dev';

function get67AuthClient() {
  if (!window.__67AuthClient) window.__67AuthClient = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_PUBLISHABLE_KEY, { auth: { flowType: 'pkce', detectSessionInUrl: true, persistSession: true, autoRefreshToken: true } });
  return window.__67AuthClient;
}
function get67RedirectUrl() { const host=window.location.hostname; const isLocal=host==='localhost'||host==='127.0.0.1'; const origin=isLocal?window.location.origin:window.SITE_URL_67; return new URL('/auth/callback.html',origin).toString(); }
window.start67GoogleAuth = async function(){try{const{error}=await get67AuthClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:get67RedirectUrl(),queryParams:{access_type:'offline',prompt:'select_account'}}});if(error)throw error}catch(error){console.error('67 Google sign-in failed:',error);if(typeof window.toast==='function')window.toast(error.message||'Google sign-in failed');else alert(error.message||'Google sign-in failed')}};
function inject67GoogleButton(){const modalBox=document.querySelector('#modal .modalbox');if(!modalBox||document.getElementById('googleAuthBtn'))return;const google=document.createElement('button');google.id='googleAuthBtn';google.className='btn';google.style.cssText='width:100%;margin:12px 0 8px;font-weight:850;';google.textContent='Continue with Google';google.addEventListener('click',()=>window.start67GoogleAuth());const divider=document.createElement('div');divider.className='sub';divider.style.cssText='text-align:center;margin:4px 0 6px;';divider.textContent='or use email';const emailInput=modalBox.querySelector('#email');if(emailInput){modalBox.insertBefore(google,emailInput);modalBox.insertBefore(divider,emailInput)}else{modalBox.prepend(divider);modalBox.prepend(google)}}
function inject67ComplianceModal(){if(document.getElementById('67ComplianceModal'))return;const modal=document.createElement('div');modal.id='67ComplianceModal';modal.className='modal open';modal.innerHTML='<div class="modalbox" style="max-width:520px"><h2>Welcome to 67 Royale</h2><p class="sub" style="line-height:1.55">67 is an 18+ internet-culture community. You can browse public content without an account, but an account is required to post, react, vote, comment, follow or enter Royale.</p><label style="display:flex;gap:8px;margin:14px 0;font-size:12px"><input id="67AgeConfirm" type="checkbox"> I confirm that I meet 67\'s minimum age requirement.</label><label style="display:flex;gap:8px;margin:14px 0;font-size:12px"><input id="67TermsConfirm" type="checkbox"> I agree to the Terms, Privacy Policy and Community Rules.</label><button id="67FinishOnboarding" class="btn primary" style="width:100%;margin-top:8px">Enter 67 Royale</button><div class="sub" style="margin-top:10px">Only confirmation timestamps are stored on your 67 profile.</div></div>';document.body.appendChild(modal);document.getElementById('67FinishOnboarding').addEventListener('click',finish67Compliance)}
async function finish67Compliance(){const age=document.getElementById('67AgeConfirm')?.checked,terms=document.getElementById('67TermsConfirm')?.checked;if(!age||!terms){toast67('Confirm your age and accept the terms first');return}const{data:{user}}=await get67AuthClient().auth.getUser();if(!user)return;const now=new Date().toISOString();const{error}=await get67AuthClient().from('profiles').update({age_confirmed_at:now,terms_accepted_at:now,privacy_accepted_at:now,community_rules_accepted_at:now}).eq('id',user.id);if(error){console.error(error);toast67('Could not save your account settings');return}document.getElementById('67ComplianceModal')?.remove();toast67('Welcome to 67 Royale')}
async function check67AccountCompliance(){const{data:{user}}=await get67AuthClient().auth.getUser();if(!user)return;const{data:profile,error}=await get67AuthClient().from('profiles').select('age_confirmed_at,terms_accepted_at,privacy_accepted_at,community_rules_accepted_at').eq('id',user.id).maybeSingle();if(error){console.warn('67 profile check failed:',error.message);return}if(!profile?.age_confirmed_at||!profile?.terms_accepted_at||!profile?.privacy_accepted_at||!profile?.community_rules_accepted_at)inject67ComplianceModal()}
function esc67(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function ago67(d){const s=Math.max(1,Math.floor((Date.now()-new Date(d))/1000));if(s<60)return s+'s';const m=Math.floor(s/60);if(m<60)return m+'m';const h=Math.floor(m/60);if(h<24)return h+'h';return Math.floor(h/24)+'d'}
function render67Post(p){const profile=p.profiles||{};const name=profile.display_name||profile.username||'67 member';const handle=profile.username?'@'+profile.username:'@member';const initial=esc67((name[0]||'6').toUpperCase());return `<article class="panel post"><div class="head"><div class="avatar">${initial}</div><div><b>${esc67(name)}</b><div class="handle">${esc67(handle)} · ${ago67(p.created_at)}</div></div></div><div class="content">${esc67(p.body).replace(/(#[a-zA-Z0-9_]+)/g,'<span class="tag">$1</span>')}</div><div class="actions"><button class="react" data-reaction="banger" data-post="${p.id}">🔥 Banger <span>${p.banger||0}</span></button><button class="react" data-reaction="skull" data-post="${p.id}">💀 <span>${p.skull||0}</span></button><button class="react" data-reaction="laugh" data-post="${p.id}">😂 <span>${p.laugh||0}</span></button><span class="score">${p.royal_score||0} 👑</span></div></article>`}
async function load67Feed(){const client=get67AuthClient();const{data,error}=await client.from('posts').select('id,author_id,body,category,royal_score,created_at,profiles(username,display_name)').order('created_at',{ascending:false}).limit(30);const feed=document.getElementById('feed');if(!feed)return;if(error){console.warn('67 feed load failed:',error.message);return}if(!data?.length)return;const postIds=data.map(p=>p.id);const{data:rx}=await client.from('reactions').select('post_id,reaction').in('post_id',postIds);const counts={};(rx||[]).forEach(r=>{const k=r.post_id+'_'+r.reaction;counts[k]=(counts[k]||0)+1});data.forEach(p=>{p.banger=counts[p.id+'_banger']||0;p.skull=counts[p.id+'_skull']||0;p.laugh=counts[p.id+'_laugh']||0});feed.innerHTML=data.map(render67Post).join('');feed.querySelectorAll('[data-reaction]').forEach(btn=>btn.addEventListener('click',()=>react67(btn.dataset.post,btn.dataset.reaction)))}
async function post67(){const text=document.getElementById('text')?.value.trim();if(!text)return toast67('Write something first');const{data:{user}}=await get67AuthClient().auth.getUser();if(!user)return typeof openAuth==='function'?openAuth():toast67('Sign in to post');const{error}=await get67AuthClient().from('posts').insert({author_id:user.id,body:text,category:'memes'});if(error){console.error(error);return toast67(error.message)}document.getElementById('text').value='';toast67('Posted to 67 Royale');await load67Feed()}
async function react67(postId,reaction){const{data:{user}}=await get67AuthClient().auth.getUser();if(!user)return typeof openAuth==='function'?openAuth():toast67('Sign in to react');const client=get67AuthClient();const{data:existing}=await client.from('reactions').select('post_id').eq('post_id',postId).eq('user_id',user.id).eq('reaction',reaction).maybeSingle();const r=existing?await client.from('reactions').delete().eq('post_id',postId).eq('user_id',user.id).eq('reaction',reaction):await client.from('reactions').insert({post_id:postId,user_id:user.id,reaction});if(r.error)toast67(r.error.message);else load67Feed()}
function toast67(t){if(typeof window.toast==='function')window.toast(t);else console.log(t)}
function install67Navigation(){const routes={'🔥 Trending':'/section.html?category=trending','⚔️ Royale':'/battle.html','🧠 67 AI':'/ai.html','🪙 Crypto':'/section.html?category=crypto','🖼️ NFTs':'/section.html?category=nfts','🎥 Streamers':'/section.html?category=streamers','🎮 Gaming':'/section.html?category=gaming','😂 Memes':null};document.querySelectorAll('.nav button').forEach(b=>{const label=b.textContent.trim();if(Object.prototype.hasOwnProperty.call(routes,label)){b.onclick=routes[label]?()=>location.href=routes[label]:()=>focusPost?.();if(label==='😂 Memes')b.remove()}});document.querySelectorAll('.logo,.brand').forEach(el=>{el.style.cursor='pointer';el.onclick=()=>location.href='/app'});if(location.pathname==='/battle.html')document.querySelectorAll('.logo').forEach(el=>el.onclick=()=>location.href='/app')}
window.addEventListener('DOMContentLoaded',()=>{inject67GoogleButton();check67AccountCompliance();load67Feed();install67Navigation();const c=get67AuthClient();c.auth.onAuthStateChange((_e,s)=>{if(s){setTimeout(check67AccountCompliance,0);setTimeout(load67Feed,100)}})});
