// Public Supabase browser configuration for 67 Royale.
window.SUPABASE_URL='https://pbokbnixktqmmtigehul.supabase.co';
window.SUPABASE_PUBLISHABLE_KEY='sb_publishable_552EmITFZ9A7XDm1P43cWg_cbSWF_Vg';
window.SITE_URL_67='https://67.mel-m-ozturk.workers.dev';
function get67AuthClient(){if(!window.__67AuthClient)window.__67AuthClient=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});return window.__67AuthClient}
function get67RedirectUrl(){const host=location.hostname,isLocal=host==='localhost'||host==='127.0.0.1';return new URL('/auth/callback.html',isLocal?location.origin:window.SITE_URL_67).toString()}
window.start67GoogleAuth=async()=>{try{const{error}=await get67AuthClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:get67RedirectUrl(),queryParams:{access_type:'offline',prompt:'select_account'}}});if(error)throw error}catch(e){console.error(e);if(typeof window.toast==='function')window.toast('Google sign-in could not start. Please try again.');else alert('Google sign-in could not start. Please try again.')}};
function inject67GoogleButton(){const box=document.querySelector('#modal .modalbox');if(!box||document.getElementById('googleAuthBtn'))return;const b=document.createElement('button');b.id='googleAuthBtn';b.className='btn';b.style.cssText='width:100%;margin:12px 0 8px;font-weight:850';b.textContent='Continue with Google';b.onclick=window.start67GoogleAuth;const d=document.createElement('div');d.className='sub';d.style.cssText='text-align:center;margin:4px 0 6px';d.textContent='or use email';const input=box.querySelector('#email');if(input){box.insertBefore(b,input);box.insertBefore(d,input)}else{box.prepend(d);box.prepend(b)}}
function toast67(t){if(typeof window.toast==='function')window.toast(t);else console.log(t)}
function install67Navigation(){const nav=document.querySelector('.nav');if(!nav)return;const items=[['🏠 Home','/app'],['🔥 Trending','/section.html?category=trending'],['⚔️ Royale','/battle.html'],['🧠 67 AI','/ai.html'],['🪙 Crypto','/section.html?category=crypto'],['🖼️ NFTs','/section.html?category=nfts'],['🎥 Streamers','/section.html?category=streamers'],['🎮 Gaming','/section.html?category=gaming'],['🔎 People','/users.html']];nav.replaceChildren(...items.map(([label,url],i)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>location.assign(url);if(i===0)b.className='active';return b}));document.querySelectorAll('.brand,.logo').forEach(el=>{el.style.cursor='pointer';el.onclick=()=>location.assign('/app')})}
function install67MobileNav(){if(document.getElementById('67MobileNav'))return;const bar=document.createElement('nav');bar.id='67MobileNav';bar.style.cssText='display:none;position:fixed;bottom:0;left:0;right:0;z-index:20;background:var(--panel);border-top:1px solid var(--line);padding:7px;grid-template-columns:repeat(5,1fr);gap:4px';[['🏠','/app'],['🔥','/section.html?category=trending'],['⚔️','/battle.html'],['🧠','/ai.html'],['👥','/users.html']].forEach(([icon,url])=>{const b=document.createElement('button');b.textContent=icon;b.style.cssText='background:transparent;border:0;padding:9px;font-size:18px';b.onclick=()=>location.assign(url);bar.appendChild(b)});document.body.appendChild(bar);const style=document.createElement('style');style.textContent='@media(max-width:700px){#67MobileNav{display:grid!important}.app{padding-bottom:76px!important}}';document.head.appendChild(style)}
function inject67ComplianceModal(){if(document.getElementById('67ComplianceModal'))return;const m=document.createElement('div');m.id='67ComplianceModal';m.className='modal open';m.innerHTML='<div class="modalbox" style="max-width:520px"><h2>Welcome to 67 Royale</h2><p class="sub" style="line-height:1.55">67 is an 18+ internet-culture community. You can browse public content without an account, but an account is required to post, react, vote, comment, follow or enter Royale.</p><label style="display:flex;gap:8px;margin:14px 0;font-size:12px"><input id="67AgeConfirm" type="checkbox"> I confirm that I meet 67\'s minimum age requirement.</label><label style="display:flex;gap:8px;margin:14px 0;font-size:12px"><input id="67TermsConfirm" type="checkbox"> I agree to the Terms, Privacy Policy and Community Rules.</label><button id="67FinishOnboarding" class="btn primary" style="width:100%">Enter 67 Royale</button></div>';document.body.appendChild(m);document.getElementById('67FinishOnboarding').onclick=finish67Compliance}
async function finish67Compliance(){if(!document.getElementById('67AgeConfirm')?.checked||!document.getElementById('67TermsConfirm')?.checked)return toast67('Confirm your age and accept the terms first');const{data:{user}}=await get67AuthClient().auth.getUser();if(!user)return;const now=new Date().toISOString();const{error}=await get67AuthClient().from('profiles').update({age_confirmed_at:now,terms_accepted_at:now,privacy_accepted_at:now,community_rules_accepted_at:now}).eq('id',user.id);if(error)return toast67('Could not save your account settings');document.getElementById('67ComplianceModal')?.remove();toast67('Welcome to 67 Royale')}
async function check67AccountCompliance(){const{data:{user}}=await get67AuthClient().auth.getUser();if(!user)return;const{data:p,error}=await get67AuthClient().from('profiles').select('age_confirmed_at,terms_accepted_at,privacy_accepted_at,community_rules_accepted_at').eq('id',user.id).maybeSingle();if(!error&&(!p?.age_confirmed_at||!p?.terms_accepted_at||!p?.privacy_accepted_at||!p?.community_rules_accepted_at))inject67ComplianceModal()}
window.addEventListener('DOMContentLoaded',()=>{inject67GoogleButton();install67Navigation();install67MobileNav();check67AccountCompliance();const c=get67AuthClient();c.auth.onAuthStateChange((_e,s)=>{if(s)setTimeout(check67AccountCompliance,0)});});
